### ISSUE TITLE
效果图和数据说明咨询

### ISSUE THREAD

**Issue by xulingling516** [ftbabi/LayersNet_ICCV2023#1]
作者你好，非常感谢你出色的工作。请问下面这种效果图，如果才能获取，有demo的代码吗？后面有开源模型的计划吗？
![image](https://github.com/ftbabi/LayersNet_ICCV2023/assets/66709839/fe01d30f-6a93-4972-90ae-12fd17e065eb)

Dataset D-LAYERS_ICCV2023 里面 meta.json 里面各个字段是否有比较详细的说明呢？

**Comment by ftbabi** [comment]
Hi您好～这个是在模型预测结果的基础上，直接用blender贴图渲染的结果。
模型会在近期开源。

数据集中的meta.json主要包含衣服的材质、以及各种属性值等，暂时不包括任何贴图的信息。
