### ISSUE TITLE
stat.h5 missing

### ISSUE THREAD

**Issue by Dolorousrtur** [ftbabi/LayersNet_ICCV2023#2]
Hi, thanks for publishing this amazing project!

I'd like to train a LayersNet model on the LAYERS dataset following your instructions.

I've downloaded the LAYERS dataset, unpacked it, and ran 
```
python tools/preprocessing_data.py configs/layersnet/base/ep1.py --work_dir *my_log_dir* --dataset test --type static
```
However, it asks for some `stat.h5` file ([this line of code](https://github.com/ftbabi/LayersNet_ICCV2023/blob/eed32b27e039fa97f4f61102f5bad2751d062edb/layersnet/datasets/layers_dynamic_dataset.py#L22)) which seems to be missing from the published dataset.

Could you help me find it?

Many thanks in advance!

**Comment by Ribosome-rbx** [comment]
hi, I'm also facing the same problem. 
I really appreciate the incredible work you've put into the LayersNet project – it's truly impressive. 
Could you please provide clarification on the availability or location of the `stat.h5` file or offer guidance on how to proceed in its absence? Your assistance would be immensely valuable.

Thank you very much for your time and consideration.

**Comment by ForrestPi** [comment]
@ftbabi 
Hi, hoping for help

**Comment by ftbabi** [comment]
Hi,

Sorry for the late reply. 

"stat.h5" is a file including the mean and std for normalizing the input data. As indicated in "Dataset Preparation" Step 2, you may run the following command to generate required data:

```python tools/preprocessing_data.py configs/layersnet/base/ep1.py --work_dir PATH/TO/LOG/DIR --dataset [train/val/test] --type dynamic```

The "stat.h5" should be generated after this command. The related codes locate at L231 in LayersNet_ICCV2023layersnet/datasets/[layers_dynamic_dataset.py](https://github.com/ftbabi/LayersNet_ICCV2023/blob/main/layersnet/datasets/layers_dynamic_dataset.py).

Best,
Yidi
